const filesInobject = {
  "Graph.js": 1,
  "Graph2.js": 2,
  "SurroundedRegions.js": 10,
  "WordLadder.js": 26,
  "alienDictionary.js": 23,
  "cheapestFlightsWithinKStops.js": 34,
  "cloneGraph.js": 35,
  "courseSchedule.js": 20,
  "courseScheduleorder.js": 21,
  "courseScheduleusingToposort.js": 22,
  "detectCycleinDirectedGraph.js": 15,
  "detectCycleinGraph.js": 7,
  "detectCycleusingTopoSort.js": 18,
  "detectCyleinGraphByDFS.js": 8,
  "dijkstraalgo.js": 29,
  "dijkstraalgousingset.js": 30,
  "eventualSafeNodes.js": 16,
  "eventualSafeNodesbytoposort.js": 19,
  "numberofProvinces.js": 3,
  "findRedundantConnection.js": 36,
  "floodFill.js": 5,
  "isBipartite.js": 14,
  "kahnAlgo.js": 18,
  "maxAreaOfIsland.js": 4,
  "minimumMultiplicationstoreachEnd.js": 35,
  "nearesrMatrix.js": 9,
  "numEnclaves.js": 12,
  "numberOfDistinctIslands.js": 13,
  "numberOfIslands.js": 4,
  "orangesRotting.js": 6,
  "pacificAtlantic.js": 11,
  "pathWithMinimumEffort.js": 33,
  "shortestDistanceinaBinaryMaze.js": 32,
  "shortestPathInWeightedUndirectedGraph.js": 31,
  "shortestPathinDirectedGraph.js": 24,
  "shortestPathinUndirectedPath.js": 25,
  "topologicalSort.js": 17,
  "wallsandgates.js": 5,
  "wordLadderii.js": 27,
  "wordladderiiforleetcode.js": 28,
};

module.exports.filesInobject = filesInobject;
